/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AgentControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentId"
      | "agentRegistered"
      | "agentSigner"
      | "cooldownPeriod"
      | "executeProposal"
      | "getProposalCount"
      | "getVaultSnapshot"
      | "identityRegistry"
      | "lastRebalanceTime"
      | "maxRebalanceBps"
      | "owner"
      | "pause"
      | "paused"
      | "proposalHistory"
      | "proposals"
      | "registerAgent"
      | "reputationRegistry"
      | "riskEngine"
      | "setAgentSigner"
      | "setCooldown"
      | "setMaxRebalanceBps"
      | "setValidatorAddress"
      | "submitProposal"
      | "transferOwnership"
      | "unpause"
      | "updateAgentURI"
      | "validationRegistry"
      | "validationTimeout"
      | "validatorAddress"
      | "vaultManager"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "EmergencyPause"
      | "EmergencyUnpause"
      | "OwnershipTransferred"
      | "ProposalExecuted"
      | "ProposalRejected"
      | "ProposalSubmitted"
      | "ReputationWritten"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agentId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "agentRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cooldownPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultSnapshot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastRebalanceTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxRebalanceBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "reputationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCooldown",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxRebalanceBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setValidatorAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProposal",
    values: [BigNumberish, BigNumberish, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAgentURI",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "validationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validationTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validatorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vaultManager",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "agentId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cooldownPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRebalanceTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRebalanceBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "riskEngine", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAgentSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxRebalanceBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setValidatorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAgentURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validationTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultManager",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [agentId: BigNumberish, agentURI: string];
  export type OutputTuple = [agentId: bigint, agentURI: string];
  export interface OutputObject {
    agentId: bigint;
    agentURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPauseEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyUnpauseEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [prev: AddressLike, next: AddressLike];
  export type OutputTuple = [prev: string, next: string];
  export interface OutputObject {
    prev: string;
    next: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [
    requestHash: BytesLike,
    fromTier: BigNumberish,
    toTier: BigNumberish,
    amount: BigNumberish,
    yieldDelta: BigNumberish
  ];
  export type OutputTuple = [
    requestHash: string,
    fromTier: bigint,
    toTier: bigint,
    amount: bigint,
    yieldDelta: bigint
  ];
  export interface OutputObject {
    requestHash: string;
    fromTier: bigint;
    toTier: bigint;
    amount: bigint;
    yieldDelta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalRejectedEvent {
  export type InputTuple = [requestHash: BytesLike, reason: string];
  export type OutputTuple = [requestHash: string, reason: string];
  export interface OutputObject {
    requestHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalSubmittedEvent {
  export type InputTuple = [
    requestHash: BytesLike,
    fromTier: BigNumberish,
    toTier: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    requestHash: string,
    fromTier: bigint,
    toTier: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    requestHash: string;
    fromTier: bigint;
    toTier: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationWrittenEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    yieldDelta: BigNumberish,
    period: string
  ];
  export type OutputTuple = [
    agentId: bigint,
    yieldDelta: bigint,
    period: string
  ];
  export interface OutputObject {
    agentId: bigint;
    yieldDelta: bigint;
    period: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentController extends BaseContract {
  connect(runner?: ContractRunner | null): AgentController;
  waitForDeployment(): Promise<this>;

  interface: AgentControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentId: TypedContractMethod<[], [bigint], "view">;

  agentRegistered: TypedContractMethod<[], [boolean], "view">;

  agentSigner: TypedContractMethod<[], [string], "view">;

  cooldownPeriod: TypedContractMethod<[], [bigint], "view">;

  executeProposal: TypedContractMethod<
    [requestHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getProposalCount: TypedContractMethod<[], [bigint], "view">;

  getVaultSnapshot: TypedContractMethod<
    [],
    [
      [
        [bigint, bigint, bigint],
        [bigint, bigint, bigint],
        [bigint, bigint, bigint],
        [bigint, bigint, bigint]
      ] & {
        tvls: [bigint, bigint, bigint];
        utilizations: [bigint, bigint, bigint];
        apys: [bigint, bigint, bigint];
        riskScores: [bigint, bigint, bigint];
      }
    ],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  lastRebalanceTime: TypedContractMethod<[], [bigint], "view">;

  maxRebalanceBps: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proposalHistory: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  proposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, string, bigint, bigint, bigint] & {
        fromTier: bigint;
        toTier: bigint;
        amount: bigint;
        requestHash: string;
        submittedAt: bigint;
        status: bigint;
        yieldDeltaBps: bigint;
      }
    ],
    "view"
  >;

  registerAgent: TypedContractMethod<[agentURI: string], [void], "nonpayable">;

  reputationRegistry: TypedContractMethod<[], [string], "view">;

  riskEngine: TypedContractMethod<[], [string], "view">;

  setAgentSigner: TypedContractMethod<
    [_signer: AddressLike],
    [void],
    "nonpayable"
  >;

  setCooldown: TypedContractMethod<
    [seconds_: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxRebalanceBps: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setValidatorAddress: TypedContractMethod<
    [_validator: AddressLike],
    [void],
    "nonpayable"
  >;

  submitProposal: TypedContractMethod<
    [
      fromTier: BigNumberish,
      toTier: BigNumberish,
      amount: BigNumberish,
      requestURI: string,
      requestHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateAgentURI: TypedContractMethod<[newURI: string], [void], "nonpayable">;

  validationRegistry: TypedContractMethod<[], [string], "view">;

  validationTimeout: TypedContractMethod<[], [bigint], "view">;

  validatorAddress: TypedContractMethod<[], [string], "view">;

  vaultManager: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentRegistered"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "agentSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cooldownPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<[requestHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getProposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaultSnapshot"
  ): TypedContractMethod<
    [],
    [
      [
        [bigint, bigint, bigint],
        [bigint, bigint, bigint],
        [bigint, bigint, bigint],
        [bigint, bigint, bigint]
      ] & {
        tvls: [bigint, bigint, bigint];
        utilizations: [bigint, bigint, bigint];
        apys: [bigint, bigint, bigint];
        riskScores: [bigint, bigint, bigint];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastRebalanceTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxRebalanceBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposalHistory"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, string, bigint, bigint, bigint] & {
        fromTier: bigint;
        toTier: bigint;
        amount: bigint;
        requestHash: string;
        submittedAt: bigint;
        status: bigint;
        yieldDeltaBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<[agentURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "riskEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAgentSigner"
  ): TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCooldown"
  ): TypedContractMethod<[seconds_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxRebalanceBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setValidatorAddress"
  ): TypedContractMethod<[_validator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitProposal"
  ): TypedContractMethod<
    [
      fromTier: BigNumberish,
      toTier: BigNumberish,
      amount: BigNumberish,
      requestURI: string,
      requestHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgentURI"
  ): TypedContractMethod<[newURI: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validationTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "validatorAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultManager"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyPause"
  ): TypedContractEvent<
    EmergencyPauseEvent.InputTuple,
    EmergencyPauseEvent.OutputTuple,
    EmergencyPauseEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyUnpause"
  ): TypedContractEvent<
    EmergencyUnpauseEvent.InputTuple,
    EmergencyUnpauseEvent.OutputTuple,
    EmergencyUnpauseEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalRejected"
  ): TypedContractEvent<
    ProposalRejectedEvent.InputTuple,
    ProposalRejectedEvent.OutputTuple,
    ProposalRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalSubmitted"
  ): TypedContractEvent<
    ProposalSubmittedEvent.InputTuple,
    ProposalSubmittedEvent.OutputTuple,
    ProposalSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationWritten"
  ): TypedContractEvent<
    ReputationWrittenEvent.InputTuple,
    ReputationWrittenEvent.OutputTuple,
    ReputationWrittenEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(uint256,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "EmergencyPause(address)": TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;
    EmergencyPause: TypedContractEvent<
      EmergencyPauseEvent.InputTuple,
      EmergencyPauseEvent.OutputTuple,
      EmergencyPauseEvent.OutputObject
    >;

    "EmergencyUnpause(address)": TypedContractEvent<
      EmergencyUnpauseEvent.InputTuple,
      EmergencyUnpauseEvent.OutputTuple,
      EmergencyUnpauseEvent.OutputObject
    >;
    EmergencyUnpause: TypedContractEvent<
      EmergencyUnpauseEvent.InputTuple,
      EmergencyUnpauseEvent.OutputTuple,
      EmergencyUnpauseEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProposalExecuted(bytes32,uint8,uint8,uint256,int128)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalRejected(bytes32,string)": TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;
    ProposalRejected: TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;

    "ProposalSubmitted(bytes32,uint8,uint8,uint256)": TypedContractEvent<
      ProposalSubmittedEvent.InputTuple,
      ProposalSubmittedEvent.OutputTuple,
      ProposalSubmittedEvent.OutputObject
    >;
    ProposalSubmitted: TypedContractEvent<
      ProposalSubmittedEvent.InputTuple,
      ProposalSubmittedEvent.OutputTuple,
      ProposalSubmittedEvent.OutputObject
    >;

    "ReputationWritten(uint256,int128,string)": TypedContractEvent<
      ReputationWrittenEvent.InputTuple,
      ReputationWrittenEvent.OutputTuple,
      ReputationWrittenEvent.OutputObject
    >;
    ReputationWritten: TypedContractEvent<
      ReputationWrittenEvent.InputTuple,
      ReputationWrittenEvent.OutputTuple,
      ReputationWrittenEvent.OutputObject
    >;
  };
}
