/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IERC8004ValidationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getValidationStatus"
      | "validationRequest"
      | "validationResponse"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getValidationStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validationRequest",
    values: [AddressLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validationResponse",
    values: [BytesLike, BigNumberish, string, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getValidationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validationRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validationResponse",
    data: BytesLike
  ): Result;
}

export interface IERC8004Validation extends BaseContract {
  connect(runner?: ContractRunner | null): IERC8004Validation;
  waitForDeployment(): Promise<this>;

  interface: IERC8004ValidationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getValidationStatus: TypedContractMethod<
    [requestHash: BytesLike],
    [
      [string, bigint, bigint, string, string, bigint] & {
        validatorAddress: string;
        agentId: bigint;
        response: bigint;
        responseHash: string;
        tag: string;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;

  validationRequest: TypedContractMethod<
    [
      validatorAddress: AddressLike,
      agentId: BigNumberish,
      requestURI: string,
      requestHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  validationResponse: TypedContractMethod<
    [
      requestHash: BytesLike,
      response: BigNumberish,
      responseURI: string,
      responseHash: BytesLike,
      tag: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getValidationStatus"
  ): TypedContractMethod<
    [requestHash: BytesLike],
    [
      [string, bigint, bigint, string, string, bigint] & {
        validatorAddress: string;
        agentId: bigint;
        response: bigint;
        responseHash: string;
        tag: string;
        lastUpdate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "validationRequest"
  ): TypedContractMethod<
    [
      validatorAddress: AddressLike,
      agentId: BigNumberish,
      requestURI: string,
      requestHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validationResponse"
  ): TypedContractMethod<
    [
      requestHash: BytesLike,
      response: BigNumberish,
      responseURI: string,
      responseHash: BytesLike,
      tag: string
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
