/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC8004Validation,
  IERC8004ValidationInterface,
} from "../../../contracts/AgentController.sol/IERC8004Validation";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestHash",
        type: "bytes32",
      },
    ],
    name: "getValidationStatus",
    outputs: [
      {
        internalType: "address",
        name: "validatorAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "response",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "responseHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "tag",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "lastUpdate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "validatorAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "requestURI",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "requestHash",
        type: "bytes32",
      },
    ],
    name: "validationRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestHash",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "response",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "responseURI",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "responseHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "tag",
        type: "string",
      },
    ],
    name: "validationResponse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC8004Validation__factory {
  static readonly abi = _abi;
  static createInterface(): IERC8004ValidationInterface {
    return new Interface(_abi) as IERC8004ValidationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC8004Validation {
    return new Contract(address, _abi, runner) as unknown as IERC8004Validation;
  }
}
