/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC8004Reputation,
  IERC8004ReputationInterface,
} from "../../../contracts/AgentController.sol/IERC8004Reputation";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "clientAddresses",
        type: "address[]",
      },
      {
        internalType: "string",
        name: "tag1",
        type: "string",
      },
      {
        internalType: "string",
        name: "tag2",
        type: "string",
      },
    ],
    name: "getSummary",
    outputs: [
      {
        internalType: "uint64",
        name: "count",
        type: "uint64",
      },
      {
        internalType: "int128",
        name: "summaryValue",
        type: "int128",
      },
      {
        internalType: "uint8",
        name: "summaryValueDecimals",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "int128",
        name: "value",
        type: "int128",
      },
      {
        internalType: "uint8",
        name: "valueDecimals",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "tag1",
        type: "string",
      },
      {
        internalType: "string",
        name: "tag2",
        type: "string",
      },
      {
        internalType: "string",
        name: "endpoint",
        type: "string",
      },
      {
        internalType: "string",
        name: "feedbackURI",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "feedbackHash",
        type: "bytes32",
      },
    ],
    name: "giveFeedback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC8004Reputation__factory {
  static readonly abi = _abi;
  static createInterface(): IERC8004ReputationInterface {
    return new Interface(_abi) as IERC8004ReputationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC8004Reputation {
    return new Contract(address, _abi, runner) as unknown as IERC8004Reputation;
  }
}
