/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRiskEngine,
  IRiskEngineInterface,
} from "../../../contracts/AgentController.sol/IRiskEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "tier",
        type: "uint8",
      },
    ],
    name: "getAverageRiskScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRiskEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IRiskEngineInterface {
    return new Interface(_abi) as IRiskEngineInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRiskEngine {
    return new Contract(address, _abi, runner) as unknown as IRiskEngine;
  }
}
