/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaultManager,
  IVaultManagerInterface,
} from "../../../contracts/AgentController.sol/IVaultManager";

const _abi = [
  {
    inputs: [],
    name: "getTotalLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "tier",
        type: "uint8",
      },
    ],
    name: "getVaultState",
    outputs: [
      {
        internalType: "uint256",
        name: "tvl",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "utilization",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentApy",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "fromTier",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "toTier",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "rebalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVaultManager__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultManagerInterface {
    return new Interface(_abi) as IVaultManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVaultManager {
    return new Contract(address, _abi, runner) as unknown as IVaultManager;
  }
}
