/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RiskEngine {
  export type RiskAssessmentStruct = {
    score: BigNumberish;
    tier: BigNumberish;
    timestamp: BigNumberish;
    validator: AddressLike;
    isValid: boolean;
  };

  export type RiskAssessmentStructOutput = [
    score: bigint,
    tier: bigint,
    timestamp: bigint,
    validator: string,
    isValid: boolean
  ] & {
    score: bigint;
    tier: bigint;
    timestamp: bigint;
    validator: string;
    isValid: boolean;
  };
}

export interface RiskEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EMERGING_MAX_SCORE"
      | "GROWTH_MAX_SCORE"
      | "PRIME_MAX_SCORE"
      | "assessmentValidityPeriod"
      | "assessments"
      | "authorizeOracle"
      | "authorizedOracles"
      | "getRiskAssessment"
      | "getTierForScore"
      | "invalidateAssessment"
      | "isAssessmentValid"
      | "owner"
      | "renounceOwnership"
      | "revokeOracle"
      | "setAssessmentValidityPeriod"
      | "submitRiskAssessment"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssessmentInvalidated"
      | "OracleAuthorized"
      | "OracleRevoked"
      | "OwnershipTransferred"
      | "RiskAssessed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EMERGING_MAX_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GROWTH_MAX_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIME_MAX_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assessmentValidityPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assessments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOracles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskAssessment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTierForScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invalidateAssessment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAssessmentValid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssessmentValidityPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRiskAssessment",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "EMERGING_MAX_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GROWTH_MAX_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIME_MAX_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assessmentValidityPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assessments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTierForScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invalidateAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAssessmentValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAssessmentValidityPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRiskAssessment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AssessmentInvalidatedEvent {
  export type InputTuple = [invoiceId: BigNumberish];
  export type OutputTuple = [invoiceId: bigint];
  export interface OutputObject {
    invoiceId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleAuthorizedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleRevokedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskAssessedEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    score: BigNumberish,
    tier: BigNumberish,
    validator: AddressLike
  ];
  export type OutputTuple = [
    invoiceId: bigint,
    score: bigint,
    tier: bigint,
    validator: string
  ];
  export interface OutputObject {
    invoiceId: bigint;
    score: bigint;
    tier: bigint;
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RiskEngine extends BaseContract {
  connect(runner?: ContractRunner | null): RiskEngine;
  waitForDeployment(): Promise<this>;

  interface: RiskEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EMERGING_MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  GROWTH_MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  PRIME_MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  assessmentValidityPeriod: TypedContractMethod<[], [bigint], "view">;

  assessments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, boolean] & {
        score: bigint;
        tier: bigint;
        timestamp: bigint;
        validator: string;
        isValid: boolean;
      }
    ],
    "view"
  >;

  authorizeOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedOracles: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getRiskAssessment: TypedContractMethod<
    [invoiceId: BigNumberish],
    [RiskEngine.RiskAssessmentStructOutput],
    "view"
  >;

  getTierForScore: TypedContractMethod<[score: BigNumberish], [bigint], "view">;

  invalidateAssessment: TypedContractMethod<
    [invoiceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  isAssessmentValid: TypedContractMethod<
    [invoiceId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setAssessmentValidityPeriod: TypedContractMethod<
    [newPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitRiskAssessment: TypedContractMethod<
    [invoiceId: BigNumberish, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EMERGING_MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GROWTH_MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRIME_MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assessmentValidityPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assessments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, boolean] & {
        score: bigint;
        tier: bigint;
        timestamp: bigint;
        validator: string;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizeOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedOracles"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRiskAssessment"
  ): TypedContractMethod<
    [invoiceId: BigNumberish],
    [RiskEngine.RiskAssessmentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTierForScore"
  ): TypedContractMethod<[score: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "invalidateAssessment"
  ): TypedContractMethod<[invoiceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isAssessmentValid"
  ): TypedContractMethod<[invoiceId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAssessmentValidityPeriod"
  ): TypedContractMethod<[newPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitRiskAssessment"
  ): TypedContractMethod<
    [invoiceId: BigNumberish, score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AssessmentInvalidated"
  ): TypedContractEvent<
    AssessmentInvalidatedEvent.InputTuple,
    AssessmentInvalidatedEvent.OutputTuple,
    AssessmentInvalidatedEvent.OutputObject
  >;
  getEvent(
    key: "OracleAuthorized"
  ): TypedContractEvent<
    OracleAuthorizedEvent.InputTuple,
    OracleAuthorizedEvent.OutputTuple,
    OracleAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OracleRevoked"
  ): TypedContractEvent<
    OracleRevokedEvent.InputTuple,
    OracleRevokedEvent.OutputTuple,
    OracleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RiskAssessed"
  ): TypedContractEvent<
    RiskAssessedEvent.InputTuple,
    RiskAssessedEvent.OutputTuple,
    RiskAssessedEvent.OutputObject
  >;

  filters: {
    "AssessmentInvalidated(uint256)": TypedContractEvent<
      AssessmentInvalidatedEvent.InputTuple,
      AssessmentInvalidatedEvent.OutputTuple,
      AssessmentInvalidatedEvent.OutputObject
    >;
    AssessmentInvalidated: TypedContractEvent<
      AssessmentInvalidatedEvent.InputTuple,
      AssessmentInvalidatedEvent.OutputTuple,
      AssessmentInvalidatedEvent.OutputObject
    >;

    "OracleAuthorized(address)": TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;
    OracleAuthorized: TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;

    "OracleRevoked(address)": TypedContractEvent<
      OracleRevokedEvent.InputTuple,
      OracleRevokedEvent.OutputTuple,
      OracleRevokedEvent.OutputObject
    >;
    OracleRevoked: TypedContractEvent<
      OracleRevokedEvent.InputTuple,
      OracleRevokedEvent.OutputTuple,
      OracleRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RiskAssessed(uint256,uint256,uint256,address)": TypedContractEvent<
      RiskAssessedEvent.InputTuple,
      RiskAssessedEvent.OutputTuple,
      RiskAssessedEvent.OutputObject
    >;
    RiskAssessed: TypedContractEvent<
      RiskAssessedEvent.InputTuple,
      RiskAssessedEvent.OutputTuple,
      RiskAssessedEvent.OutputObject
    >;
  };
}
