/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VaultManager {
  export type InvestorPositionStruct = {
    depositedAmount: BigNumberish;
    shares: BigNumberish;
    depositTimestamp: BigNumberish;
    claimedReturns: BigNumberish;
  };

  export type InvestorPositionStructOutput = [
    depositedAmount: bigint,
    shares: bigint,
    depositTimestamp: bigint,
    claimedReturns: bigint
  ] & {
    depositedAmount: bigint;
    shares: bigint;
    depositTimestamp: bigint;
    claimedReturns: bigint;
  };

  export type VaultStruct = {
    tier: BigNumberish;
    totalDeposits: BigNumberish;
    totalAllocated: BigNumberish;
    totalReturns: BigNumberish;
    minDeposit: BigNumberish;
    maxRiskScore: BigNumberish;
    advanceRate: BigNumberish;
    isActive: boolean;
  };

  export type VaultStructOutput = [
    tier: bigint,
    totalDeposits: bigint,
    totalAllocated: bigint,
    totalReturns: bigint,
    minDeposit: bigint,
    maxRiskScore: bigint,
    advanceRate: bigint,
    isActive: boolean
  ] & {
    tier: bigint;
    totalDeposits: bigint;
    totalAllocated: bigint;
    totalReturns: bigint;
    minDeposit: bigint;
    maxRiskScore: bigint;
    advanceRate: bigint;
    isActive: boolean;
  };
}

export interface VaultManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "PLATFORM_FEE"
      | "deposit"
      | "fundInvoice"
      | "getAvailableLiquidity"
      | "getPosition"
      | "getTotalShares"
      | "getVault"
      | "getVaultTierForRisk"
      | "invoiceAllocations"
      | "invoiceFunding"
      | "invoiceNFT"
      | "owner"
      | "positions"
      | "processRepayment"
      | "renounceOwnership"
      | "setVaultActive"
      | "stablecoin"
      | "transferOwnership"
      | "updateVaultParameters"
      | "vaults"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InvoiceFunded"
      | "InvoiceRepaid"
      | "OwnershipTransferred"
      | "VaultDeposit"
      | "VaultWithdrawal"
      | "YieldDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundInvoice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultTierForRisk",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invoiceAllocations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invoiceFunding",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invoiceNFT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processRepayment",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVaultParameters",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultTierForRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invoiceAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invoiceFunding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invoiceNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVaultParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace InvoiceFundedEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    tier: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [invoiceId: bigint, tier: bigint, amount: bigint];
  export interface OutputObject {
    invoiceId: bigint;
    tier: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceRepaidEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    amount: BigNumberish,
    yield_: BigNumberish
  ];
  export type OutputTuple = [invoiceId: bigint, amount: bigint, yield_: bigint];
  export interface OutputObject {
    invoiceId: bigint;
    amount: bigint;
    yield: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultDepositEvent {
  export type InputTuple = [
    investor: AddressLike,
    tier: BigNumberish,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    tier: bigint,
    amount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    investor: string;
    tier: bigint;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultWithdrawalEvent {
  export type InputTuple = [
    investor: AddressLike,
    tier: BigNumberish,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    tier: bigint,
    amount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    investor: string;
    tier: bigint;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldDistributedEvent {
  export type InputTuple = [tier: BigNumberish, totalYield: BigNumberish];
  export type OutputTuple = [tier: bigint, totalYield: bigint];
  export interface OutputObject {
    tier: bigint;
    totalYield: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultManager extends BaseContract {
  connect(runner?: ContractRunner | null): VaultManager;
  waitForDeployment(): Promise<this>;

  interface: VaultManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [tier: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundInvoice: TypedContractMethod<
    [invoiceId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAvailableLiquidity: TypedContractMethod<
    [tier: BigNumberish],
    [bigint],
    "view"
  >;

  getPosition: TypedContractMethod<
    [tier: BigNumberish, investor: AddressLike],
    [VaultManager.InvestorPositionStructOutput],
    "view"
  >;

  getTotalShares: TypedContractMethod<[tier: BigNumberish], [bigint], "view">;

  getVault: TypedContractMethod<
    [tier: BigNumberish],
    [VaultManager.VaultStructOutput],
    "view"
  >;

  getVaultTierForRisk: TypedContractMethod<
    [riskScore: BigNumberish],
    [bigint],
    "view"
  >;

  invoiceAllocations: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  invoiceFunding: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  invoiceNFT: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  positions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        depositedAmount: bigint;
        shares: bigint;
        depositTimestamp: bigint;
        claimedReturns: bigint;
      }
    ],
    "view"
  >;

  processRepayment: TypedContractMethod<
    [invoiceId: BigNumberish, repaymentAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setVaultActive: TypedContractMethod<
    [tier: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  stablecoin: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateVaultParameters: TypedContractMethod<
    [
      tier: BigNumberish,
      minDeposit: BigNumberish,
      maxRiskScore: BigNumberish,
      advanceRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  vaults: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        tier: bigint;
        totalDeposits: bigint;
        totalAllocated: bigint;
        totalReturns: bigint;
        minDeposit: bigint;
        maxRiskScore: bigint;
        advanceRate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<
    [tier: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [tier: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundInvoice"
  ): TypedContractMethod<[invoiceId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAvailableLiquidity"
  ): TypedContractMethod<[tier: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [tier: BigNumberish, investor: AddressLike],
    [VaultManager.InvestorPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalShares"
  ): TypedContractMethod<[tier: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [tier: BigNumberish],
    [VaultManager.VaultStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultTierForRisk"
  ): TypedContractMethod<[riskScore: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "invoiceAllocations"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "invoiceFunding"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "invoiceNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        depositedAmount: bigint;
        shares: bigint;
        depositTimestamp: bigint;
        claimedReturns: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "processRepayment"
  ): TypedContractMethod<
    [invoiceId: BigNumberish, repaymentAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultActive"
  ): TypedContractMethod<
    [tier: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVaultParameters"
  ): TypedContractMethod<
    [
      tier: BigNumberish,
      minDeposit: BigNumberish,
      maxRiskScore: BigNumberish,
      advanceRate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        tier: bigint;
        totalDeposits: bigint;
        totalAllocated: bigint;
        totalReturns: bigint;
        minDeposit: bigint;
        maxRiskScore: bigint;
        advanceRate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [tier: BigNumberish, shares: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "InvoiceFunded"
  ): TypedContractEvent<
    InvoiceFundedEvent.InputTuple,
    InvoiceFundedEvent.OutputTuple,
    InvoiceFundedEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceRepaid"
  ): TypedContractEvent<
    InvoiceRepaidEvent.InputTuple,
    InvoiceRepaidEvent.OutputTuple,
    InvoiceRepaidEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VaultDeposit"
  ): TypedContractEvent<
    VaultDepositEvent.InputTuple,
    VaultDepositEvent.OutputTuple,
    VaultDepositEvent.OutputObject
  >;
  getEvent(
    key: "VaultWithdrawal"
  ): TypedContractEvent<
    VaultWithdrawalEvent.InputTuple,
    VaultWithdrawalEvent.OutputTuple,
    VaultWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "YieldDistributed"
  ): TypedContractEvent<
    YieldDistributedEvent.InputTuple,
    YieldDistributedEvent.OutputTuple,
    YieldDistributedEvent.OutputObject
  >;

  filters: {
    "InvoiceFunded(uint256,uint8,uint256)": TypedContractEvent<
      InvoiceFundedEvent.InputTuple,
      InvoiceFundedEvent.OutputTuple,
      InvoiceFundedEvent.OutputObject
    >;
    InvoiceFunded: TypedContractEvent<
      InvoiceFundedEvent.InputTuple,
      InvoiceFundedEvent.OutputTuple,
      InvoiceFundedEvent.OutputObject
    >;

    "InvoiceRepaid(uint256,uint256,uint256)": TypedContractEvent<
      InvoiceRepaidEvent.InputTuple,
      InvoiceRepaidEvent.OutputTuple,
      InvoiceRepaidEvent.OutputObject
    >;
    InvoiceRepaid: TypedContractEvent<
      InvoiceRepaidEvent.InputTuple,
      InvoiceRepaidEvent.OutputTuple,
      InvoiceRepaidEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VaultDeposit(address,uint8,uint256,uint256)": TypedContractEvent<
      VaultDepositEvent.InputTuple,
      VaultDepositEvent.OutputTuple,
      VaultDepositEvent.OutputObject
    >;
    VaultDeposit: TypedContractEvent<
      VaultDepositEvent.InputTuple,
      VaultDepositEvent.OutputTuple,
      VaultDepositEvent.OutputObject
    >;

    "VaultWithdrawal(address,uint8,uint256,uint256)": TypedContractEvent<
      VaultWithdrawalEvent.InputTuple,
      VaultWithdrawalEvent.OutputTuple,
      VaultWithdrawalEvent.OutputObject
    >;
    VaultWithdrawal: TypedContractEvent<
      VaultWithdrawalEvent.InputTuple,
      VaultWithdrawalEvent.OutputTuple,
      VaultWithdrawalEvent.OutputObject
    >;

    "YieldDistributed(uint8,uint256)": TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
    YieldDistributed: TypedContractEvent<
      YieldDistributedEvent.InputTuple,
      YieldDistributedEvent.OutputTuple,
      YieldDistributedEvent.OutputObject
    >;
  };
}
